server:
  port: 8080

spring:
  application:
    name: workerconnect

  datasource:
    url: jdbc:postgresql://localhost:5432/workerconnect?autoReconnect=true&useSSL=false
    username: postgres
    password: seaface
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: false
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true